### ISSUE TITLE
create: hex() argument can't be converted to hex

### ISSUE THREAD

**Issue by jorisbontje** [etherex/pyepm#2]
```
$ ./cli.py create
Traceback (most recent call last):
  File "./cli.py", line 6, in <module>
    sleth.cli.main()
  File "/Users/mids/Projects/Foundry/sleth/sleth/cli.py", line 65, in main
    args.func(args)
  File "/Users/mids/Projects/Foundry/sleth/sleth/cli.py", line 16, in cmd_create
    contract_address = instance.create(contract)
  File "/Users/mids/.virtualenvs/sleth/lib/python2.7/site-packages/pyepm/api.py", line 92, in create
    'gas': hex(gas),
TypeError: hex() argument can't be converted to hex
```

`api.py` should probably be modified to use `str` instead of `hex`; or `config.getint` should be used to cast the `gas` and `gasprice` variables to integer.

**Comment by caktux** [comment]
Had already done so for transact and call using `str`, will apply to `create` also.

**Comment by caktux** [comment]
Done in 0.8.1
